server:
  port: 8443
  ssl:
    key-store: classpath:mykeystore.jks
    key-alias: myalias
    enabled: true
    key-store-type: JKS
    key-store-password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    useGeneratedKeys: true
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZylLx930101
    url: jdbc:mysql://192.168.31.243:13306/local?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
  threads:
    virtual:
      enabled: true
logging:
  config: classpath:logback-spring.xml